'use client';
import { useMemo, useState } from 'react';
import { ArrowDownUp, ArrowUpRight, Download, Plus, Search, Trash2, Users, TrendingUp, Target, CircleCheck, MapPin } from 'lucide-react';
import { DemoShell, Feedback, Loading, Modal, PageTitle } from '@/components/demos/shared';
import { useWorkspace } from '@/lib/use-workspace';
import { stages, type Prospect } from '@/lib/demo-data';
import { download, exportPdf } from '@/lib/download';
const money = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);
export default function Prospects() {
  const work = useWorkspace('prospects');
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All prospects'); const [sort, setSort] = useState<'company' | 'value'>('company');
  const [editing, setEditing] = useState<Prospect | null>(null); const [confirmDelete, setConfirmDelete] = useState(false); const [view, setView] = useState('Pipeline');
  const rows = useMemo(() => (work.data?.prospects || []).filter(p => `${p.company} ${p.contact} ${p.city}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'All prospects' || p.stage === filter) && (view !== 'Follow-ups' || (p.nextAction && !['Won','Lost'].includes(p.stage)))).sort((a,b) => sort === 'value' ? b.value - a.value : a.company.localeCompare(b.company)), [work.data, query, filter, sort, view]);
  const newProspect = () => { setConfirmDelete(false); setEditing({ id: crypto.randomUUID(), company: '', contact: '', email: '', phone: '', city: '', territory: 'West Michigan', owner: 'You', stage: 'New', value: 0, nextAction: '', notes: '', updated: new Date().toISOString() }); };
  const save = async () => {
    if (!editing || !work.data) return;
    const item = { ...editing, company: editing.company.trim(), contact: editing.contact.trim(), updated: new Date().toISOString() };
    const exists = work.data.prospects.some(p => p.id === item.id);
    const result = await work.save({ prospects: exists ? work.data.prospects.map(p => p.id === item.id ? item : p) : [...work.data.prospects, item] }, exists ? 'Prospect updated' : 'Prospect created');
    if (result) setEditing(null);
  };
  const exportRows = () => {
    const cell = (value: unknown) => `"${String(value).replace(/^[=+@-]/, "'").replace(/"/g, '""')}"`;
    const csv = [['Company','Contact','Email','City','Stage','Value','Next action'], ...rows.map(p => [p.company,p.contact,p.email,p.city,p.stage,p.value,p.nextAction])].map(row => row.map(cell).join(',')).join('\r\n');
    download(new Blob([csv], { type: 'text/csv;charset=utf-8' }), 'prospects.csv'); work.setNotice('Filtered prospects exported');
  };
  const patch = <K extends keyof Prospect>(key: K, value: Prospect[K]) => setEditing(p => p ? { ...p, [key]: value } : p);
  return <DemoShell active="Prospects"><PageTitle title="Customer prospects" description="Good relationships start with the next conversation."><button className="secondary" onClick={exportRows} disabled={!work.data}><Download size={16}/>Export</button><button className="primary" onClick={newProspect} disabled={!work.data}><Plus size={17}/>New prospect</button></PageTitle>
    <Feedback error={work.error} notice={work.notice}/>{!work.data ? <Loading error={work.error} retry={work.reload}/> : <>
    <div className="stats-row">{[
      { label: 'Total prospects', value: work.data.prospects.length, detail: 'In your demo workspace', icon: Users },
      { label: 'Active pipeline', value: money(work.data.prospects.filter(p => !['Won','Lost'].includes(p.stage)).reduce((s,p) => s+p.value,0)), detail: 'Across open opportunities', icon: TrendingUp },
      { label: 'Qualified', value: work.data.prospects.filter(p => p.stage === 'Qualified').length, detail: 'Ready for a closer look', icon: Target },
      { label: 'Won', value: money(work.data.prospects.filter(p => p.stage === 'Won').reduce((s,p) => s+p.value,0)), detail: 'Closed opportunities', icon: CircleCheck },
    ].map(stat => <div className="stat" key={stat.label}><div><span>{stat.label}</span><stat.icon size={17}/></div><strong>{stat.value}</strong><small>{stat.detail}</small></div>)}</div>
    <div className="view-tabs">{['Pipeline', 'Follow-ups', 'Reports'].map(v => <button key={v} className={view === v ? 'selected' : ''} onClick={() => setView(v)}>{v}</button>)}</div>
    {view === 'Reports' ? <section className="surface report-view"><h2>Pipeline by stage</h2><p className="muted">A live breakdown of your workspace.</p>{stages.map(stage => { const group = work.data!.prospects.filter(p => p.stage === stage); return <div className="report-row" key={stage}><span className={`status status-${stage.toLowerCase()}`}>{stage}</span><div className="report-track"><i style={{ width: `${group.length / Math.max(work.data!.prospects.length,1) * 100}%` }}/></div><b>{group.length}</b><span>{money(group.reduce((s,p) => s+p.value,0))}</span></div>; })}<button className="secondary" disabled={work.busy} onClick={() => void work.run(() => exportPdf('Prospect pipeline report', 'Fictional sales workspace', stages.map(stage => { const group = work.data!.prospects.filter(p => p.stage === stage); return `${stage}: ${group.length} prospects | ${money(group.reduce((s,p) => s+p.value,0))}`; }).join('\n\n'), 'pipeline-report.pdf'), 'Report downloaded')}><Download size={16}/>Download report</button></section> : <>
    <div className="table-toolbar"><label className="search-field"><Search size={17}/><input aria-label="Search prospects" placeholder="Search companies, contacts, or cities…" value={query} onChange={e => setQuery(e.target.value)}/></label><select aria-label="Filter by stage" value={filter} onChange={e => setFilter(e.target.value)}>{['All prospects',...stages].map(s => <option key={s}>{s}</option>)}</select><button className="secondary" onClick={() => setSort(sort === 'company' ? 'value' : 'company')}><ArrowDownUp size={15}/>{sort === 'company' ? 'Company' : 'Value'}</button></div>
    <div className="table-surface"><table className="prospects-table"><thead><tr><th>Company / contact</th><th>Stage</th><th>Location</th><th>Potential value</th><th>Next action</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{rows.filter(p => view !== 'Follow-ups' || (p.nextAction && !['Won','Lost'].includes(p.stage))).map(p => <tr key={p.id}><td><button className="company-cell" onClick={() => { setEditing({ ...p }); setConfirmDelete(false); }}><span className="company-avatar">{p.company.split(' ').slice(0,2).map(w => w[0]).join('')}</span><span><strong>{p.company}</strong><small>{p.contact}</small></span></button></td><td><span className={`status status-${p.stage.toLowerCase()}`}>{p.stage}</span></td><td><span className="location-cell"><MapPin size={13}/>{p.city || 'Not set'}</span><small>{p.territory}</small></td><td className="numeric">{money(p.value)}</td><td className="next-action">{p.nextAction || 'Add a next step'}</td><td><button className="icon-button" aria-label={`Open ${p.company}`} onClick={() => { setEditing({ ...p }); setConfirmDelete(false); }}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table>{rows.length === 0 && <div className="empty-state"><h3>No prospects found</h3><p>Try another search or add a prospect.</p></div>}<div className="table-bottom"><span>{rows.length} prospects in this view</span><span>Fictional companies · real workflow</span></div></div></>}
    </>}
    {editing && <Modal title={work.data?.prospects.some(p => p.id === editing.id) ? editing.company : 'New prospect'} onClose={() => !work.busy && setEditing(null)}><form onSubmit={e => { e.preventDefault(); void save(); }}><div className="form-grid"><label>Company<input required maxLength={100} value={editing.company} onChange={e => patch('company',e.target.value)}/></label><label>Contact name<input required maxLength={100} value={editing.contact} onChange={e => patch('contact',e.target.value)}/></label><label>Email<input type="email" value={editing.email} onChange={e => patch('email',e.target.value)}/></label><label>Phone<input maxLength={30} value={editing.phone} onChange={e => patch('phone',e.target.value)}/></label><label>City<input maxLength={100} value={editing.city} onChange={e => patch('city',e.target.value)}/></label><label>Territory<select value={editing.territory} onChange={e => patch('territory',e.target.value)}>{['West Michigan','Northern Michigan','Central Michigan','Southeast Michigan','Other'].map(t => <option key={t}>{t}</option>)}</select></label><label>Stage<select value={editing.stage} onChange={e => patch('stage',e.target.value as Prospect['stage'])}>{stages.map(s => <option key={s}>{s}</option>)}</select></label><label>Potential value ($)<input type="number" min={0} max={10000000} value={editing.value} onChange={e => patch('value',Number(e.target.value))}/></label></div><label>Next action<input maxLength={300} value={editing.nextAction} onChange={e => patch('nextAction',e.target.value)}/></label><label>Activity notes<textarea rows={4} maxLength={8000} value={editing.notes} onChange={e => patch('notes',e.target.value)}/></label><Feedback error={work.error} notice=""/><div className="modal-actions">{work.data?.prospects.some(p => p.id === editing.id) && <button type="button" className="danger-button" disabled={work.busy} onClick={() => { if (!confirmDelete) setConfirmDelete(true); else void work.save({ prospects: work.data!.prospects.filter(p => p.id !== editing.id) }, 'Prospect deleted').then(result => { if (result) setEditing(null); }); }}><Trash2 size={16}/>{confirmDelete ? 'Confirm delete' : 'Delete'}</button>}<button type="button" className="secondary" onClick={() => setEditing(null)}>Cancel</button><button className="primary" disabled={work.busy}>{work.busy ? 'Saving…' : 'Save prospect'}</button></div></form></Modal>}
  </DemoShell>;
}
