'use client';
import { useState } from 'react';
import { Check, Download, FileText, Save, Sparkles, Trash2, Upload } from 'lucide-react';
import { DemoShell, Feedback, Loading, PageTitle } from '@/components/demos/shared';
import { useWorkspace, type Snapshot } from '@/lib/use-workspace';
import { api } from '@/lib/api';
import { exportPdf, readDocument } from '@/lib/download';
import type { WorkspaceData } from '@/lib/demo-data';
export default function Rfp() {
  const work = useWorkspace('rfp'); const [draft, setDraft] = useState<WorkspaceData<'rfp'> | null>(null); const [section, setSection] = useState(0); const [tab, setTab] = useState('Response');
  const data = draft || work.data;
  const save = async () => { if (!data) return; const result = await work.save(data); if (result) setDraft(null); return result; };
  const generate = async () => { if (!await save()) return; const result = await work.run(() => api<Snapshot<'rfp'>>('/ai/generate', { kind: 'rfp', section }), 'Section drafted from your reference material'); if (result) { work.setSnapshot(result); setDraft(null); } };
  const upload = async (file: File) => { if (!data) return; const source = await work.run(() => readDocument(file)); if (source) { setDraft({ ...data, sources: [...data.sources, source] }); work.setNotice('Reference added. Save or generate a section to keep it.'); } };
  return <DemoShell active="RFP workspace"><PageTitle title="A stronger response starts with the source." description="Help your construction team turn company qualifications and project references into high-quality responses to requests for proposals."><button className="secondary" disabled={!data || work.busy} onClick={() => void save()}><Save size={16}/>Save</button><button className="primary" disabled={!data?.sections.some(s => s.body) || work.busy} onClick={() => void work.run(() => exportPdf(data!.title, `Prepared for ${data!.client}`, data!.sections.map(s => `${s.title}\n\n${s.body || 'To be completed.'}`).join('\n\n\n'), 'rfp-response.pdf'), 'Response downloaded')}><Download size={16}/>Export response</button></PageTitle><Feedback error={work.error} notice={work.notice}/>{!data ? <Loading error={work.error} retry={work.reload}/> : <>
    <div className="rfp-meta surface"><label>Proposal name<input maxLength={200} value={data.title} onChange={e => setDraft({ ...data, title: e.target.value })}/></label><label>Client<input maxLength={200} value={data.client} onChange={e => setDraft({ ...data, client: e.target.value })}/></label><div className="completion"><strong>{data.sections.filter(s => s.body).length} / 3</strong><span>Sections drafted</span></div></div>
    <div className="rfp-layout"><aside className="surface rfp-sources"><h2>Reference library</h2><p className="muted">The facts your response is built on.</p>{data.sources.map((s,i) => <div className="source-file" key={`${s.name}-${i}`}><FileText size={20}/><div><strong>{s.name}</strong><small>{s.text.length.toLocaleString()} characters</small></div><button className="icon-button" aria-label={`Remove ${s.name}`} disabled={work.busy} onClick={() => setDraft({ ...data, sources: data.sources.filter((_,j) => i!==j) })}><Trash2 size={14}/></button></div>)}<label className={`upload-zone ${work.busy || data.sources.length >= 5 ? 'disabled' : ''}`}><Upload size={22}/><strong>Add reference material</strong><span>PDF, TXT, or Markdown · up to 5 MB</span><input aria-label="Upload reference document" type="file" accept=".pdf,.txt,.md" disabled={work.busy || data.sources.length >= 5} onChange={e => { if (e.target.files?.[0]) void upload(e.target.files[0]); e.target.value = ''; }}/></label><div className="source-note"><Check size={16}/><p>Only your uploaded references inform the response. Missing evidence is marked “To confirm.”</p></div></aside>
    <section className="surface rfp-editor"><div className="view-tabs">{['Response','Requirements','Preview'].map(t => <button key={t} className={tab === t ? 'selected' : ''} onClick={() => setTab(t)}>{t}</button>)}</div>{tab === 'Requirements' ? <div className="rfp-editor-body"><h2>What the client needs</h2><label>RFP requirements<textarea rows={16} maxLength={16000} value={data.requirements} onChange={e => setDraft({ ...data, requirements: e.target.value })}/></label></div> : tab === 'Preview' ? <article className="rfp-preview"><h2>{data.title}</h2><p className="muted">Prepared for {data.client}</p>{data.sections.map(s => <section key={s.title}><h3>{s.title}</h3><p className="prose-text">{s.body || 'This section has not been drafted yet.'}</p></section>)}</article> : <><div className="section-nav">{data.sections.map((s,i) => <button key={s.title} className={section === i ? 'selected' : ''} onClick={() => setSection(i)}><span>{s.body ? <Check size={13}/> : i+1}</span>{s.title}</button>)}</div><div className="rfp-editor-body"><div className="section-editor-heading"><h2>{data.sections[section].title}</h2><button className="primary" disabled={work.busy || !data.sources.length} onClick={() => void generate()}><Sparkles size={16}/>{work.busy ? 'Drafting…' : data.sections[section].body ? 'Redraft section' : 'Draft section'}</button></div><label className="sr-only" htmlFor="rfp-body">Section response</label><textarea id="rfp-body" className="rfp-textarea" rows={18} maxLength={12000} value={data.sections[section].body} placeholder="Generate a grounded first draft, then make it your own. Source references will appear alongside the response." onChange={e => setDraft({ ...data, sections: data.sections.map((s,i) => i === section ? { ...s, body: e.target.value } : s) })}/><div className="editor-status"><span>{draft ? 'Unsaved changes' : 'All changes saved'}</span><span>{data.sections[section].body.length.toLocaleString()} characters</span></div></div></>}</section></div>
    </>}
  </DemoShell>;
}
