'use client';

import { useState } from 'react';
import { ArrowUpRight, Check, Globe, Monitor, Save, Smartphone } from 'lucide-react';
import { DemoShell, Feedback, Loading, PageTitle } from '@/components/demos/shared';
import { SitePreview } from '@/components/demos/site-preview';
import { useWorkspace } from '@/lib/use-workspace';
import type { WorkspaceData } from '@/lib/demo-data';
export default function Cms() {
  const work = useWorkspace('cms'); const [draft, setDraft] = useState<WorkspaceData<'cms'>['draft'] | null>(null); const [mobile, setMobile] = useState(false);
  const page = draft || work.data?.draft;
  const patch = <K extends keyof NonNullable<typeof page>>(key: K, value: NonNullable<typeof page>[K]) => { if (page) setDraft({ ...page, [key]: value }); };
  const save = async (publish = false) => { if (!work.data || !page) return; const result = await work.save({ ...work.data, draft: page, ...(publish ? { published: structuredClone(page), revision: work.data.revision + 1, publishedAt: new Date().toISOString() } : {}) }, publish ? 'Page published. Open the published version to see it.' : 'Draft saved'); if (result) setDraft(null); };
  return <DemoShell active="Content studio"><PageTitle title="Your words. Your space." description="Edit a page, see the changes, and publish when it feels right."><button className="secondary" disabled={!page || work.busy} onClick={() => void save()}><Save size={16}/>Save draft</button><button className="primary" disabled={!page || work.busy} onClick={() => void save(true)}><Globe size={16}/>{work.busy ? 'Saving…' : 'Publish page'}</button></PageTitle><Feedback error={work.error} notice={work.notice}/>{!page || !work.data ? <Loading error={work.error} retry={work.reload}/> : <div className="cms-layout"><section className="surface cms-fields"><header><h2>Homepage</h2><span className="status status-qualified">Editable</span></header><label>Brand name<input maxLength={100} value={page.brand} onChange={e => patch('brand',e.target.value)}/></label><label>Headline<textarea rows={3} maxLength={200} value={page.headline} onChange={e => patch('headline',e.target.value)}/></label><label>Description<textarea rows={5} maxLength={2000} value={page.description} onChange={e => patch('description',e.target.value)}/></label><label>Button label<input maxLength={60} value={page.button} onChange={e => patch('button',e.target.value)}/></label><label>Contact email<input type="email" value={page.email} onChange={e => patch('email',e.target.value)}/></label><fieldset className="color-field"><legend>Accent color</legend>{(['blue','green','rose'] as const).map(color => <button type="button" key={color} className={`color-swatch swatch-${color}`} aria-label={`${color} accent`} aria-pressed={page.accent === color} onClick={() => patch('accent',color)}>{page.accent === color && <Check size={17}/>}</button>)}</fieldset><div className="publish-status"><span>Published version {work.data.revision}</span><small>{work.data.publishedAt ? new Date(work.data.publishedAt).toLocaleString() : 'Sample page'}</small><a href="/cms/published/">Open published page <ArrowUpRight size={15}/></a></div></section><section className="cms-preview-column"><div className="preview-browser"><span className="browser-dots">● ● ●</span><span>Live draft preview</span><div><button className={`icon-button ${!mobile ? 'selected' : ''}`} aria-label="Desktop preview" onClick={() => setMobile(false)}><Monitor size={18}/></button><button className={`icon-button ${mobile ? 'selected' : ''}`} aria-label="Mobile preview" onClick={() => setMobile(true)}><Smartphone size={18}/></button></div></div><div className={`cms-canvas ${mobile ? 'mobile-canvas' : ''}`}><SitePreview page={page}/></div><p className="small-copy muted">Draft changes appear here immediately. The published page updates only when you publish.</p></section></div>}</DemoShell>;
}
