
import { ArrowUpRight, Github, Linkedin, FileText, Headphones, LayoutTemplate, Sparkles, Check, ArrowRight } from 'lucide-react';
export default function Home() {
  return <div className="portfolio"><header className="portfolio-nav"><a href="/" className="personal-logo">jw<span>.</span></a><nav aria-label="Main navigation"><a href="#work">Selected work</a><a href="#approach">About</a><a href="mailto:jake@syncgr.com" className="contact-link">Let’s talk <ArrowUpRight size={16}/></a></nav></header>
    <main><section className="portfolio-hero"><div className="hero-intro"><span className="availability-dot"/>Jake Worsham · Grand Rapids, Michigan</div><h1>Ideas into<br/><span>working software.</span></h1><div className="hero-bottom"><p>I work across product, design, and engineering at Sync. These are hands-on demonstrations of the tools I build: useful software for real business problems.</p><a className="round-link" href="#work" aria-label="Explore the projects"><ArrowRight size={30}/></a></div></section>
    <section id="work" className="work-section"><div className="section-heading"><h2>Open a project. Make something happen.</h2><p>Working demos, with a fresh workspace for you.</p></div>
      <div className="featured-grid"><a className="work-project prospect-preview" href="/prospects/"><div className="project-caption"><div><span>Sales operations</span><h3>Prospects</h3></div><ArrowUpRight/></div><div className="mini-portal" aria-hidden="true"><div className="mini-side"><b>workspace<span>.</span></b><p>Overview</p><p className="selected">Prospects</p><p>Activity</p><p>Reports</p></div><div className="mini-main"><div className="mini-top"><span>Your next conversation starts here.</span><span>+ New prospect</span></div><h4>Customer prospects</h4><div className="mini-stats"><div><small>Active pipeline</small><b>$122,000</b></div><div><small>Qualified</small><b>2 prospects</b></div></div>{['Juniper Market', 'Northline Provisions', 'Fieldwork Coffee', 'Cedar & Main'].map((name, i) => <div className="mini-row" key={name}><span className="mini-avatar">{name[0]}</span><b>{name}</b><span className={`mini-pill pill-${i}`}>{['Qualified', 'Proposal', 'Contacted', 'New'][i]}</span></div>)}</div></div><div className="project-bottom">Create a prospect. Move a deal forward. <span>Try the workspace <ArrowUpRight size={16}/></span></div></a>
      <a className="work-project helga-preview" href="/helga/"><div className="project-caption"><div><span>Personal AI assistant</span><h3>Helga</h3></div><ArrowUpRight/></div><div className="mini-helga" aria-hidden="true"><div className="mini-helga-greeting">A little more space<br/>to think.</div><div className="orb still"><i/><i/><i/><div className="orb-core"/></div><div className="mini-prompt">What’s on my agenda today?<span>↵</span></div><div className="mini-task"><Check size={13}/> Morning planning, handled.</div></div><div className="project-bottom">Speak naturally. Get things done.<span>Meet Helga <ArrowUpRight size={16}/></span></div></a></div>
      <div className="supporting-grid">{[
        { href: 'receptionist', icon: Headphones, name: 'AI receptionist', category: 'Voice & customer experience', text: 'Have a conversation, capture a request, and leave a useful callback note.' },
        { href: 'documents', icon: FileText, name: 'Document automation', category: 'Notes to deliverables', text: 'Turn rough meeting notes into an editable proposal and a finished PDF.' },
        { href: 'rfp', icon: Sparkles, name: 'RFP workspace', category: 'AI with reference material', text: 'Bring the source documents. Draft, refine, and export a grounded response.' },
        { href: 'cms', icon: LayoutTemplate, name: 'Content studio', category: 'Publishing tools', text: 'Edit a page, see it take shape, and publish a version you can open.' },
      ].map(p => <a className="supporting-project" href={`/${p.href}/`} key={p.href}><div className={`project-icon icon-${p.href}`}><p.icon size={25}/></div><span>{p.category}</span><h3>{p.name}<ArrowUpRight size={20}/></h3><p>{p.text}</p><b>Open demo</b></a>)}</div>
    </section>
    <section id="approach" className="about-section"><div><span className="about-kicker">The person behind the work</span><h2>Good software starts<br/>with a good question.</h2></div><div><p>My work starts with understanding what someone needs to get done. From there, I bring together design, code, and AI to make the process easier to use.</p><p>At Sync, I collaborate across customer discovery, product design, and implementation. This portfolio recreates selected workflows in isolated demo environments, so you can explore the experience yourself.</p><div className="about-links"><a href="https://github.com/Jakew9697" target="_blank" rel="noreferrer"><Github size={18}/>GitHub</a><a href="https://linkedin.com/in/jakeworsham" target="_blank" rel="noreferrer"><Linkedin size={18}/>LinkedIn</a></div></div></section>
    <section className="contact-section"><p>Have something worth building?</p><a href="mailto:jake@syncgr.com">Let’s talk.<ArrowUpRight/></a></section></main><footer className="portfolio-footer"><span>© {new Date().getFullYear()} Jake Worsham</span><span>Designed to be tried.</span></footer>
  </div>;
}
