'use client';
import { useState } from 'react';
import { ArrowUp, CalendarDays, Check, CheckCheck, Circle, FilePenLine, ListTodo, Plus, Trash2 } from 'lucide-react';
import { DemoShell, Feedback, Loading, Modal } from '@/components/demos/shared';
import { ListenButton, RecordButton } from '@/components/demos/voice';
import { useWorkspace, type Snapshot } from '@/lib/use-workspace';
import { api } from '@/lib/api';
import type { WorkspaceData } from '@/lib/demo-data';
export default function Helga() {
  const work = useWorkspace('helga'); const [input, setInput] = useState(''); const [voiceState, setVoiceState] = useState('idle'); const [draft, setDraft] = useState<WorkspaceData<'helga'>['drafts'][number] | null>(null);
  const send = async (message = input) => {
    if (!message.trim() || work.busy) return;
    const result = await work.run(() => api<Snapshot<'helga'> & { answer: string; actions: string[] }>('/ai/helga', { message }));
    if (result) { work.setSnapshot(result); setInput(''); work.setNotice(result.actions.join(' · ')); }
  };
  return <DemoShell active="Helga" helga><div className="helga-heading"><div><span>Your day, a little lighter.</span><h1>Hello, visitor.</h1><p>A quiet place to think, plan, and get things done.</p></div><div className="helga-date"><CalendarDays size={17}/><span>Your demo day</span></div></div><Feedback error={work.error} notice={work.notice}/>
    {!work.data ? <Loading error={work.error} retry={work.reload}/> : <>
    <div className="helga-dashboard"><section className="helga-widget"><header><h2><ListTodo size={17}/>Your focus</h2><span>{work.data.tasks.filter(t => t.done).length}/{work.data.tasks.length}</span></header><div className="task-list">{work.data.tasks.map(task => <div className={`task-row ${task.done ? 'done' : ''}`} key={task.id}><button disabled={work.busy} aria-label={`${task.done ? 'Reopen' : 'Complete'} ${task.title}`} onClick={() => void work.save({ ...work.data!, tasks: work.data!.tasks.map(t => t.id === task.id ? { ...t, done: !t.done } : t) }, task.done ? 'Task reopened' : 'Task completed')}>{task.done ? <Check size={15}/> : <Circle size={15}/>}<span>{task.title}</span></button><button className="icon-button" disabled={work.busy} aria-label={`Delete task ${task.title}`} onClick={() => void work.save({ ...work.data!, tasks: work.data!.tasks.filter(t => t.id !== task.id) }, 'Task removed')}><Trash2 size={13}/></button></div>)}</div><button className="text-button" onClick={() => setInput('Add a task to ')}><Plus size={14}/>Ask Helga to add a task</button></section>
    <section className="helga-center"><div className={`orb ${work.busy || voiceState !== 'idle' ? 'active' : 'still'}`} aria-hidden="true"><i/><i/><i/><div className="orb-core"/></div><div className="orb-state" role="status">{work.busy ? 'Thinking with you…' : voiceState === 'recording' ? 'Listening…' : voiceState === 'transcribing' ? 'Finding your words…' : 'A little help, whenever you need it.'}</div><RecordButton disabled={work.busy} onText={text => { setInput(text); void send(text); }} onError={work.setError} onState={setVoiceState}/><p className="mic-hint">Tap to record · up to 30 seconds</p></section>
    <section className="helga-widget agenda-widget"><header><h2><CalendarDays size={17}/>On the calendar</h2><span>{work.data.events.length} events</span></header><div className="agenda-list">{work.data.events.map(event => <div className="agenda-item" key={event.id}><time>{event.time}</time><div><span className="agenda-dot"/><strong>{event.title}</strong></div></div>)}</div><button className="text-button" onClick={() => setInput('Add a calendar event for ')}><Plus size={14}/>Make a little space</button></section></div>
    <div className="helga-lower"><section className="helga-conversation"><header><h2>A conversation with Helga</h2><span>Tasks, plans, and drafts</span></header><div className="conversation-messages" aria-live="polite">{work.data.messages.length ? work.data.messages.map((message,i) => <div className={`chat-message ${message.role}`} key={i}><small>{message.role === 'user' ? 'You' : 'Helga'}</small><p>{message.text}</p>{message.role === 'assistant' && <ListenButton text={message.text} onError={work.setError}/>}</div>) : <div className="conversation-empty"><p>What would you like to make room for?</p><div className="suggestions">{['Help me plan my day', 'Add a task to review the portfolio', 'Draft a short project update'].map(text => <button key={text} disabled={work.busy} onClick={() => { setInput(text); void send(text); }}>{text}</button>)}</div></div>}{work.busy && <div className="thinking" role="status">Helga is working on it<span>…</span></div>}</div><form className="chat-form" onSubmit={e => { e.preventDefault(); void send(); }}><input aria-label="Message Helga" placeholder="Ask Helga anything about your day…" value={input} onChange={e => setInput(e.target.value)} maxLength={4000}/><button className="primary icon-button" aria-label="Send to Helga" disabled={work.busy || !input.trim()}><ArrowUp size={20}/></button></form></section>
    <section className="helga-widget drafts-widget"><header><h2><FilePenLine size={17}/>Drafts, ready when you are</h2></header>{work.data.drafts.length ? work.data.drafts.map(d => <button className="draft-item" key={d.id} onClick={() => setDraft(d)}><strong>{d.subject}</strong><span>{d.body.slice(0,100)}…</span></button>) : <div className="draft-empty"><FilePenLine size={26}/><p>Turn a thought into a first draft.</p><span>Ask Helga to draft an email. It stays here for you to review.</span></div>}<div className="widget-footnote"><CheckCheck size={14}/>Drafts are saved here; no emails are sent.</div></section></div>
    </>}{draft && <Modal title={draft.subject} onClose={() => setDraft(null)}><div className="prose-text">{draft.body}</div><div className="modal-actions"><button className="primary" onClick={() => { void navigator.clipboard.writeText(draft.body).then(() => work.setNotice('Draft copied')).catch(() => work.setError('Could not copy. Select the draft text to copy manually.')); }}>Copy draft</button></div></Modal>}
  </DemoShell>;
}
